version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: bill_spliiter_postgres
    restart: always
    environment:
      POSTGRES_DB: bill_splitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9376570167
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: